Repository apollographql/apollo-tooling, pull requests merged in 2018-07, with the labels that each got.

#470 Restore ability to put generated files in a directory relative to source
  packages/apollo-cli/README.md
  packages/apollo-cli/package.json
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/generate.ts
Labels: blocking, feature

#477 Add lerna-changelog to manage generating changelogs
  package-lock.json
  package.json
Labels: internal

#479 Run `build` before publishing to prevent uploading stale code
  package-lock.json
  packages/apollo-cli/package.json
  packages/apollo-codegen-core/package.json
  packages/apollo-codegen-flow-legacy/package.json
  packages/apollo-codegen-flow/package.json
  packages/apollo-codegen-scala/package.json
  packages/apollo-codegen-swift/package.json
  packages/apollo-codegen-typescript-legacy/package.json
  packages/apollo-codegen-typescript/package.json
Labels: internal

#480 Initial support for client-side schemas
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideOnlyQuery.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideOnlySchema.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchema.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchemaQuery.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/commands/schema/__tests__/__snapshots__/download.test.ts.snap
  packages/apollo-cli/src/commands/schema/__tests__/check.test.ts
  packages/apollo-cli/src/commands/schema/__tests__/download.test.ts
  packages/apollo-cli/src/commands/schema/__tests__/fixtures/schema.graphql
  packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts
  packages/apollo-cli/src/fetch-schema.ts
  packages/apollo-cli/src/generate.ts
  packages/apollo-cli/src/printer/__tests__/__snapshots__/print.ts.snap
  packages/apollo-cli/src/validation.ts
  packages/apollo-codegen-core/src/compiler/index.ts
Labels: feature

#483 Support generating based on .graphql schema files
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/fetch-schema.ts
Labels: feature

#485 Support loading server-side schema from JS/TS files
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/fetch-schema.ts
Labels: feature

#488 Handle cases when storing server-defined models in local state
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchema.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/fixtures/clientSideSchemaQuery.graphql
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-codegen-core/src/compiler/index.ts
Labels: bug

#490 Assume the output is a directory when it has no extension
  packages/apollo-cli/src/generate.ts
Labels: feature

#489 Remove unused locals in Apollo CLI
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/commands/queries/check.ts
  packages/apollo-cli/src/commands/schema/check.ts
  packages/apollo-cli/src/commands/schema/publish.ts
  packages/apollo-cli/src/engine-cli.ts
  packages/apollo-cli/src/fetch-schema.ts
  packages/apollo-cli/src/generate.ts
  packages/apollo-cli/src/git.ts
  packages/apollo-cli/src/printer/ast.ts
  packages/apollo-cli/src/printer/diff.ts
  packages/apollo-cli/src/printer/print.tsx
  packages/apollo-cli/tsconfig.json
Labels: internal

#484 Support file watching for codegen:generate
  package-lock.json
  packages/apollo-cli/@types/gaze.d.ts
  packages/apollo-cli/package.json
  packages/apollo-cli/src/commands/codegen/generate.ts
Labels: feature

#492 Make TypeScript options more consistent across packages
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts
  packages/apollo-cli/tsconfig.json
  tsconfig.base.json
Labels: internal

#497 Load config from apollo.config.js or package.json
  package-lock.json
  packages/apollo-cli/package-lock.json
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/commands/queries/__tests__/check.test.ts
  packages/apollo-cli/src/commands/queries/check.ts
  packages/apollo-cli/src/commands/schema/__tests__/__snapshots__/download.test.ts.snap
  packages/apollo-cli/src/commands/schema/__tests__/download.test.ts
  packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts
  packages/apollo-cli/src/commands/schema/check.ts
  packages/apollo-cli/src/commands/schema/download.ts
  packages/apollo-cli/src/commands/schema/publish.ts
  packages/apollo-cli/src/config.ts
  packages/apollo-cli/src/fetch-schema.ts
  packages/apollo-cli/src/load-config.ts
  packages/apollo-cli/src/load-schema.ts
  packages/apollo-codegen-core/package.json
  packages/apollo-codegen-core/src/loading.ts
Labels: feature

#504 Add Apollo VS Code extension
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  packages/apollo-language-server/copy-apollo-libs.sh
  packages/apollo-language-server/package.json
  packages/apollo-language-server/src/diagnostics.ts
  packages/apollo-language-server/src/document.ts
  packages/apollo-language-server/src/format.ts
  packages/apollo-language-server/src/languageProvider.ts
  packages/apollo-language-server/src/project.ts
  packages/apollo-language-server/src/server.ts
  packages/apollo-language-server/src/typings/graphql-language-service.d.ts
  packages/apollo-language-server/src/typings/graphql.d.ts
  packages/apollo-language-server/src/utilities/graphql.ts
  packages/apollo-language-server/src/utilities/source.ts
  packages/apollo-language-server/src/workspace.ts
  packages/apollo-language-server/tsconfig.json
  packages/apollo-vscode/graphql.configuration.json
  packages/apollo-vscode/package-lock.json
  packages/apollo-vscode/package.json
  packages/apollo-vscode/src/extension.ts
  packages/apollo-vscode/syntaxes/graphql.js.json
  packages/apollo-vscode/syntaxes/graphql.json
  packages/apollo-vscode/tsconfig.json
Labels: feature

#506 Share validation logic between CLI and language server
  .vscode/launch.json
  packages/apollo-cli/src/validation.ts
  packages/apollo-language-server/src/diagnostics.ts
Labels: internal

#505 Add docs for Apollo config
  packages/apollo-cli/README.md
Labels: docs

#508 Support jumping to definitions in schema
  packages/apollo-cli/src/commands/schema/__tests__/check.test.ts
  packages/apollo-cli/src/commands/schema/__tests__/publish.test.ts
  packages/apollo-cli/src/commands/schema/check.ts
  packages/apollo-cli/src/commands/schema/download.ts
  packages/apollo-cli/src/commands/schema/publish.ts
  packages/apollo-cli/src/config.ts
  packages/apollo-cli/src/fetch-schema.ts
  packages/apollo-cli/src/load-schema.ts
  packages/apollo-language-server/src/languageProvider.ts
  packages/apollo-language-server/src/project.ts
  packages/apollo-language-server/src/workspace.ts
  packages/apollo-vscode/package-lock.json
  packages/apollo-vscode/src/extension.ts
Labels: feature

#515 Fix missing descriptions and add more hover information for arguments
  packages/apollo-language-server/src/languageProvider.ts
  packages/apollo-language-server/src/project.ts
  packages/apollo-vscode/syntaxes/graphql.json
Labels: feature

#516 Code complete default query variables
  package-lock.json
  packages/apollo-language-server/package.json
  packages/apollo-language-server/src/document.ts
  packages/apollo-language-server/src/languageProvider.ts
  packages/apollo-language-server/src/project.ts
  packages/apollo-language-server/src/typings/graphql-language-service.d.ts
Labels: feature

#511 Stop default flag values from overriding custom config
  packages/apollo-cli/src/load-config.ts
Labels: bug

#518 [typescript] Only output comment for input if there is one
  packages/apollo-codegen-typescript/src/language.ts
Labels: feature

#519 [VSCode] Fix detection of projects inside folders
  packages/apollo-cli/src/config.ts
  packages/apollo-language-server/src/workspace.ts
  packages/apollo-vscode/package-lock.json
Labels: bug
