Repository apollographql/apollo-tooling, pull requests merged in 2018-08, with the labels that each got.

#524 Fixed broken command links
  packages/apollo-cli/README.md
  packages/apollo-cli/package.json
Labels: docs

#525 [TS] Elimate newlines at beginning of file and add newline at end of file
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/generate.ts
  packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap
  packages/apollo-codegen-typescript/src/printer.ts
Labels: feature

#521 Add README for the VS Code extension
  packages/apollo-cli/README.md
  packages/apollo-vscode/README.md
  packages/apollo-vscode/images/engine-stats.png
  packages/apollo-vscode/images/icon-apollo-teal-400x400.png
  packages/apollo-vscode/images/query-with-vars.gif
  packages/apollo-vscode/images/variable-argument-completion.gif
  packages/apollo-vscode/package.json
  packages/apollo-vscode/src/extension.ts
Labels: docs

#533 Fall back to other methods of schema loading when one fails
  packages/apollo-cli/src/load-schema.ts
Labels: feature

#536 Display status of loading tasks for config and Engine stats
  packages/apollo-language-server/copy-apollo-libs.sh
  packages/apollo-language-server/src/languageProvider.ts
  packages/apollo-language-server/src/project.ts
  packages/apollo-language-server/src/server.ts
  packages/apollo-language-server/src/workspace.ts
  packages/apollo-vscode/src/extension.ts
Labels: feature

#535 [TS] Sort global types so order is not determined by order of appearance
  packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap
  packages/apollo-codegen-typescript/src/codeGeneration.ts
Labels: feature

#544 Prepend ./ to TS relative paths to make them valid, fix #543
  packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap
  packages/apollo-codegen-typescript/src/codeGeneration.ts
Labels: bug

#546 [TS] Added outputGlobalTypes option to specify path for global types
  packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap
  packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts
  packages/apollo-cli/src/commands/codegen/generate.ts
  packages/apollo-cli/src/commands/schema/__tests__/__snapshots__/download.test.ts.snap
  packages/apollo-cli/src/commands/schema/__tests__/fixtures/schema.graphql
  packages/apollo-cli/src/generate.ts
  packages/apollo-cli/src/printer/__tests__/__snapshots__/print.ts.snap
Labels: feature
